// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAeQsupXwkBXu5V2t_oRFnl_iVxth8a8M',
    appId: '1:1073743428450:web:149424a5af6788cfed4a3b',
    messagingSenderId: '1073743428450',
    projectId: 'gasis-app',
    authDomain: 'gasis-app.firebaseapp.com',
    storageBucket: 'gasis-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sGXePlNV6QaZhAsry2dx-vB_k-rq74k',
    appId: '1:1073743428450:android:d327f2ed6874de92ed4a3b',
    messagingSenderId: '1073743428450',
    projectId: 'gasis-app',
    storageBucket: 'gasis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSrGajv1SBbjznXSzK_qdexfNRb-iMUk',
    appId: '1:1073743428450:ios:4a56e29f3359a3c9ed4a3b',
    messagingSenderId: '1073743428450',
    projectId: 'gasis-app',
    storageBucket: 'gasis-app.firebasestorage.app',
    iosBundleId: 'com.example.testGasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZSrGajv1SBbjznXSzK_qdexfNRb-iMUk',
    appId: '1:1073743428450:ios:4a56e29f3359a3c9ed4a3b',
    messagingSenderId: '1073743428450',
    projectId: 'gasis-app',
    storageBucket: 'gasis-app.firebasestorage.app',
    iosBundleId: 'com.example.testGasis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAeQsupXwkBXu5V2t_oRFnl_iVxth8a8M',
    appId: '1:1073743428450:web:b9bc530cd1ad0581ed4a3b',
    messagingSenderId: '1073743428450',
    projectId: 'gasis-app',
    authDomain: 'gasis-app.firebaseapp.com',
    storageBucket: 'gasis-app.firebasestorage.app',
  );

}